PL/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Threading.Tasks;//Metodos asincronos

namespace PL.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        //[HttpGet]
        //public ActionResult GetAll()
        //{
        //    ML.Result result = BL.Alumno.GetAll();
        //    ML.Alumno alumno = new ML.Alumno();
        //    alumno.Alumnos = result.Objects.ToList();
        //    return View(alumno);
        //}
        //WebService WCF
        //=======================================================================
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            try
            {
                ServiceReferenceAlumno.AlumnoClient alumnoClient = new ServiceReferenceAlumno.AlumnoClient();
                var result = alumnoClient.GetAll();
                alumno.Alumnos = result.Objects.ToList();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View(alumno);
        }
        //Asincrono
        /*[HttpGet]
        public async Task<ActionResult> GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            try
            {
                ServiceReferenceAlumno.AlumnoClient alumnoClient = new ServiceReferenceAlumno.AlumnoClient();
                var result = await alumnoClient.GetAllAsync();
                alumno.Alumnos = result.Objects.ToList();

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View(alumno);
        }*/
        //=======================================================================
        //WebAPI
        //=======================================================================
        [HttpGet]
        public ActionResult GetAllAPI()
        {
            ML.Alumno alumno = new ML.Alumno();
            alumno.Alumnos = new List<object>();
            using (var cliente = new HttpClient())
            {
                cliente.BaseAddress = new Uri("http://localhost:50404/");
                var responseTask = cliente.GetAsync("api/alumno");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();
                    foreach (var item in readTask.Result.Objects)
                    {
                        ML.Alumno resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Alumno>(item.ToString());
                        alumno.Alumnos.Add(resultItemList);
                    }
                }
            }
            return View(alumno);
        }
        //=======================================================================
        /*[HttpGet]
        public ActionResult Form(int? IdAlumno)
        {
            ML.Result result = new ML.Result();
            ML.Alumno alumno = new ML.Alumno();
            if (IdAlumno==null)
            {
                return View(alumno);
            }
            else
            {
                result = BL.Alumno.GetById(IdAlumno.Value);
                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                    return View(alumno);
                }
                else
                {
                    ViewBag.Message = result.ErrorMessage;
                    return PartialView("Modal");//aprende a crear el modal, es un mensaje generico para errores
                }
            }
        }
        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            ML.Result result = new ML.Result();
            if (alumno.IdAlumno==0)
            {
                result = BL.Alumno.Add(alumno);
                ViewBag.Message = "Agregado con exito";
            }
            else
            {
                result = BL.Alumno.Update(alumno);
                ViewBag.Message = "Actualizado";
            }
            if (!result.Correct)
            {
                ViewBag.Message = result.ErrorMessage;
            }
            return PartialView("Modal");
        }*/
        [HttpGet]
        public ActionResult Form(int? IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();
            if (IdAlumno==null)
            {
                return View(alumno);
            }
            else
            {
                try
                {
                    using (var cliente = new HttpClient())
                    {
                        cliente.BaseAddress = new Uri("http://localhost:50404/");
                        var responseTask = cliente.GetAsync("api/alumno/" + IdAlumno);
                        responseTask.Wait();
                        var result = responseTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            var readTask = result.Content.ReadAsAsync<ML.Result>();
                            readTask.Wait();
                            ML.Alumno alumnoItem = new ML.Alumno();
                            alumnoItem = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Alumno>(readTask.Result.Object.ToString());
                            alumno = alumnoItem;
                        }
                        else
                        {
                            ViewBag.Message = "Ocurrio error con servicio";
                            return PartialView("Modal");
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.Message;
                }
            }
            return View(alumno);
        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            try
            {
                using (var cliente = new HttpClient())
                {
                    cliente.BaseAddress = new Uri("http://localhost:50404/");
                    if (alumno.IdAlumno == 0)
                    {
                        var postTask = cliente.PostAsJsonAsync<ML.Alumno>("api/alumno", alumno);
                        postTask.Wait();
                        var result = postTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            return RedirectToAction("GetAll");
                        }
                    }
                    else
                    {
                        var putTask = cliente.PutAsJsonAsync<ML.Alumno>("api/alumno/" + alumno.IdAlumno, alumno);
                        putTask.Wait();
                        var result = putTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            return RedirectToAction("GetAll");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return PartialView("Modal");
            }
            return View("GetAll");// estoy en duda puede ser redirect 
        }
    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        //metodo de prueba
        public ActionResult Test()
        {


            return View();
        }
    }
}

PL/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
}

<div class="container">
    <div class=" row">
        <h5>Alumno</h5>
    </div>
    <div class="row">
        @using(Html.BeginForm("Form","Alumno", FormMethod.Post, new {enctype="multipart/form-data" }))
        {
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.IdAlumno, new { @class="hidden"})
                        @Html.ValidationMessageFor(model => model.IdAlumno)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Nombre)
                        @Html.TextBoxFor(model => model.Nombre, new { @class="form-control"})
                        @Html.ValidationMessageFor(model => model.Nombre)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        @Html.TextBoxFor(model=>model.ApellidoPaterno, new { @class="form-control"})
                        @Html.ValidationMessageFor(model =>model.ApellidoPaterno)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        @Html.TextBoxFor(model=>model.ApellidoMaterno, new { @class="form-control"})
                        @Html.ValidationMessageFor(model=>model.ApellidoMaterno)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <input type="submit" name="Guardar" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar","GetAll","Alumno",htmlAttributes: new {@class="btn btn-danger "})
                    </div>
                </div>
            </div>
        }
    </div>
</div>

PL/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
}


<div class="jumbotron text-center">
    <h2>GetAll</h2>    
</div>
<div class="container">
    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+","Form","Alumno", htmlAttributes: new {@class="btn btn-success" })
        </div>
        <table class="table table-responsive table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Editar</th>
                    <th class="hidden">IdAlumno</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Apellido Paterno</th>
                    <th class="text-center">Apellido Materno</th>
                    <th class="text-center">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit " href="@Url.Action("Form","Alumno", new {IdAlumno=alumno.IdAlumno })"></a></td>
                        <td class="hidden">@alumno.IdAlumno</td>
                        <td class="text-center">@alumno.Nombre</td>
                        <td class="text-center">@alumno.ApellidoPaterno</td>
                        <td class="text-center">@alumno.ApellidoMaterno</td>
                        <td class="text-center"><a class=" btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete","Alumno",new {IdAlumno=alumno.IdAlumno })" onclick="return confirm('Esta seguro de eliminar');"></a></td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Alumno", "GetAll", "Alumno")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>